### ISSUE TITLE
Redundancy of dependacies...

### ISSUE THREAD

**Issue by GordonBGood** [eeue56/elm-lazy-list#3]
This library depends on a bastardized non-memoizing version of Lazy, which is redundant in that it no longer does anything, but only contains a constant thunk.

This type may as well be formulated to contain the thunk directly, and rather than calling the redundant "force" which calls the thunk, call the thunk directly to lessen the number of nested calls.

**Comment by eeue56** [comment]
This is true, and I've thought about this before. The thing is that elm-lazy existing is good going forward, so that people stop tripping on the old libraries once the update to 0.19 comes.
