### ISSUE TITLE
Meant to be used by test; testing of library depends on test:  circular dependency

### ISSUE THREAD

**Issue by GordonBGood** [eeue56/elm-lazy-list#6]
Tests in this library (such as they are) depend on the test library, but the stated purpose of the library is to be used by the test library.

If this is desired, an alternate means of testing needs to be used, such as an HTML page as I use in my PR for community/elm-lazy-list.

**Comment by eeue56** [comment]
Circular dependencies aren't an issue. There's no problem past bootstrapping. Many frameworks do things this way.
